const genericTags = [
    { value: 'javascript', label: 'JavaScript' },
    { value: 'python', label: 'Python' },
    { value: 'java', label: 'Java' },
    { value: 'csharp', label: 'C#' },
    { value: 'ruby', label: 'Ruby' },
    { value: 'php', label: 'PHP' },
    { value: 'typescript', label: 'TypeScript' },
    { value: 'swift', label: 'Swift' },
    { value: 'objectivec', label: 'Objective-C' },
    { value: 'kotlin', label: 'Kotlin' },
    { value: 'go', label: 'Go' },
    { value: 'rust', label: 'Rust' },
    { value: 'scala', label: 'Scala' },
    { value: 'perl', label: 'Perl' },
    { value: 'haskell', label: 'Haskell' },
    { value: 'elixir', label: 'Elixir' },
    { value: 'clojure', label: 'Clojure' },
    { value: 'fsharp', label: 'F#' },
    { value: 'dart', label: 'Dart' },
    { value: 'lua', label: 'Lua' },
    { value: 'matlab', label: 'MATLAB' },
    { value: 'r', label: 'R' },
    { value: 'sas', label: 'SAS' },
    { value: 'vba', label: 'VBA' },
    { value: 'solidity', label: 'Solidity' },
    { value: 'erlang', label: 'Erlang' },
    { value: 'groovy', label: 'Groovy' },
    { value: 'smalltalk', label: 'Smalltalk' },
    { value: 'cobol', label: 'COBOL' },
    { value: 'fortran', label: 'Fortran' },
    { value: 'ada', label: 'Ada' },
    { value: 'pascal', label: 'Pascal' },
    { value: 'assembly', label: 'Assembly' },
    { value: 'bash', label: 'Bash' },
    { value: 'shell', label: 'Shell' },
    { value: 'powershell', label: 'PowerShell' },
    { value: 'html', label: 'HTML' },
    { value: 'css', label: 'CSS' },
    { value: 'xml', label: 'XML' },
    { value: 'json', label: 'JSON' },
    { value: 'mysql', label: 'MySQL' },
    { value: 'postgresql', label: 'PostgreSQL' },
    { value: 'mongodb', label: 'MongoDB' },
    { value: 'redis', label: 'Redis' },
    { value: 'sqlite', label: 'SQLite' },
    { value: 'oracle', label: 'Oracle' },
    { value: 'sqlserver', label: 'SQL Server' },
    { value: 'firebase', label: 'Firebase' },
    { value: 'aws', label: 'AWS' },
    { value: 'azure', label: 'Azure' },
    { value: 'gcp', label: 'Google Cloud Platform' },
    { value: 'heroku', label: 'Heroku' },
    { value: 'docker', label: 'Docker' },
    { value: 'kubernetes', label: 'Kubernetes' },
    { value: 'jenkins', label: 'Jenkins' },
    { value: 'terraform', label: 'Terraform' },
    { value: 'ansible', label: 'Ansible' },
    { value: 'puppet', label: 'Puppet' },
    { value: 'chef', label: 'Chef' },
    { value: 'rabbitmq', label: 'RabbitMQ' },
    { value: 'kafka', label: 'Kafka' },
    { value: 'spark', label: 'Apache Spark' },
    { value: 'hadoop', label: 'Hadoop' },
    { value: 'elasticsearch', label: 'Elasticsearch' },
    { value: 'logstash', label: 'Logstash' },
    { value: 'kibana', label: 'Kibana' },
    { value: 'grafana', label: 'Grafana' },
    { value: 'prometheus', label: 'Prometheus' },
    { value: 'nginx', label: 'NGINX' },
    { value: 'apache', label: 'Apache HTTP Server' },
    { value: 'iis', label: 'IIS' },
    { value: 'tomcat', label: 'Apache Tomcat' },
    { value: 'jetty', label: 'Jetty' },
    { value: 'weblogic', label: 'WebLogic' },
    { value: 'glassfish', label: 'GlassFish' },
    { value: 'wildfly', label: 'WildFly' },
    { value: 'spring', label: 'Spring Framework' },
    { value: 'django', label: 'Django' },
    { value: 'flask', label: 'Flask' },
    { value: 'rails', label: 'Ruby on Rails' },
    { value: 'laravel', label: 'Laravel' },
    { value: 'express', label: 'Express.js' },
    { value: 'angular', label: 'Angular' },
    { value: 'react', label: 'React' },
    { value: 'vue', label: 'Vue.js' },
    { value: 'svelte', label: 'Svelte' },
    { value: 'ember', label: 'Ember.js' },
    { value: 'backbone', label: 'Backbone.js' },
    { value: 'jquery', label: 'jQuery' },
    { value: 'bootstrap', label: 'Bootstrap' },
    { value: 'tailwind', label: 'Tailwind CSS' },
];

const officeTags = [
    { value: 'frontend', label: 'Desenvolvedor Frontend' },
    { value: 'backend', label: 'Desenvolvedor Backend' },
    { value: 'fullstack', label: 'Desenvolvedor FullStack' },
    { value: 'web-developer', label: 'Desenvolvedor Web' },
    { value: 'software-developer', label: 'Desenvolvedor de Software' },
    { value: 'systems-analyst', label: 'Anlista de Sistemas' },
    { value: 'computer-engineer', label: 'Engenheiro da Computação' },
    { value: 'data-engineer', label: 'Engenheiro de Dados' },
    { value: 'database-administrator', label: 'Administrador de Banco de Dados' },
    { value: 'data-scientist', label: 'Cientista de Dados' },
    { value: 'mobile-developer', label: 'Desenvolvedor Mobile' },
    { value: 'cyber-security', label: 'Segurança da Informação' },
];

export { genericTags, officeTags }